platform: yr

homeassistant: !include custom/homeassistant.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

########## INCLUDE all the files for our customization ###############

# Z-Wave is pre-installed in the docker-container already, so we just need to set it up
zwave: !include custom/zwave.yaml
automation: !include custom/automation.yaml
zone: !include custom/zones.yaml
sensor: !include custom/sensors.yaml
switch: !include custom/switches.yaml
device_tracker: !include custom/device_tracker.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation: !include custom/conversation.yaml

# Discover some devices automatically
discovery: !include custom/discovery.yaml

http: !include custom/http.yaml
