platform: yr

homeassistant: !include custom/homeassistant.yaml

discovery:
sun:
updater:
frontend:
conversation:
logbook:
zeroconf:
history:

########## INCLUDE all the files for our customization ###############
# credits to https://github.com/cbulock/home-assistant-configs .. also see his configuration
# for more examples

zwave: !include custom/zwave.yaml
automation: !include_dir_list custom/automation
groups: !include_dir_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
http: !include custom/http.yaml

# activate those only, if you actually put something there!!!!

#notify: !include notify.yaml
#device_tracker: !include custom/device_tracker.yaml
